name: Create issues from todos

on:
  push:
    branches:
      - master

jobs:
  todos:
    runs-on: ubuntu-latest
    steps:     
      - uses: actions/checkout@v2

      - uses: wvffle/todo-actions@master
        with:
          collect_commit_msg: 'ci: collect new todos'
          reference_commit_msg: 'ci: add references to new todos'
          reference_commit_body: 'New issues: %s'
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          TODO_ACTIONS_MONGO_URL: ${{ secrets.TODO_ACTIONS_MONGO_URL }}
